folders:
  - ./:
      struct:
        - github/prompts/struct
        - github/workflows/pre-commit
        - github/workflows/release-drafter
        - github/workflows/labeler
        - configs/prettier
        - configs/editor-config
