files:
  - main.yml:
      content: |
        - name: Example Playbook
          hosts: all
          become: yes
          roles:
            - example-role
  - vars.yml:
      content: |
        example_variable: "value"
  - tasks/main.yml:
      content: |
        - name: Install packages
          apt:
            name: "{{ item }}"
            state: present
          with_items:
            - git
            - curl
  - handlers/main.yml:
      content: |
        - name: Restart service
          service:
            name: example-service
            state: restarted
  - templates/README.md:
      content: |
        # Example Template
        This template contains example configuration files.
  - README.md:
      content: |
        # Playbook Name
        This playbook installs necessary packages and configures services.
        ## Usage
        ```bash
        ansible-playbook -i inventory main.yml
        ```
